/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#eac349',
        'surface-container-highest': '#0B211D',
        'on-secondary': '#00382b',
        outline: '#8b938d',
        'tertiary-fixed': '#ffe088',
        'secondary-container': '#02b894',
        'primary-container': '#0d3b2a',
        'primary-fixed': '#beedd4',
        'on-primary': '#083827',
        'inverse-surface': '#e5e2e1',
        'on-tertiary': '#3c2f00',
        'surface-container-high': '#0B211D',
        'surface-dim': '#081815',
        'on-primary-container': '#79a68f',
        'inverse-primary': '#3c6753',
        'on-secondary-fixed-variant': '#005140',
        'surface-container-lowest': '#081815',
        surface: '#0B211D',
        'on-primary-fixed': '#002115',
        'on-surface': '#e5e2e1',
        'on-tertiary-container': '#4f3e00',
        'surface-tint': '#a2d1b9',
        'surface-container-low': '#0B211D',
        secondary: '#4bddb7',
        'on-background': '#e5e2e1',
        'primary-fixed-dim': '#a2d1b9',
        'secondary-fixed': '#6dfad2',
        'outline-variant': '#414944',
        'tertiary-fixed-dim': '#e9c349',
        'on-tertiary-fixed': '#241a00',
        'on-secondary-container': '#004233',
        'secondary-fixed-dim': '#4bddb7',
        background: '#081815',
        'on-surface-variant': '#c0c8c2',
        'on-error': '#690005',
        'on-primary-fixed-variant': '#234f3c',
        'error-container': '#93000a',
        'inverse-on-surface': '#313030',
        error: '#ffb4ab',
        'on-secondary-fixed': '#002018',
        'on-tertiary-fixed-variant': '#574500',
        primary: '#a2d1b9',
        'surface-variant': '#0B211D',
        'tertiary-container': '#cca830',
        'surface-container': '#0B211D',
        'surface-bright': '#0B211D',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
        base: '8px',
        'container-max': '1440px',
      },
      fontFamily: {
        'display-lg': ['Cairo'],
        'headline-md': ['Cairo'],
        'display-lg-mobile': ['Cairo'],
        'body-lg': ['Plus Jakarta Sans'],
        'label-caps': ['Geist'],
        'body-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
